version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '5672:${RABBITMQ_PORT:-5672}'
      - '15672:${RABBITMQ_MANAGEMENT_PORT:-15672}'
    env_file: .env

  collector-ps2:
    build: apps/stream-collector
    env_file: apps/stream-collector/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - PS2_ENVIRONMENT=ps2
    restart: unless-stopped
    networks:
      - ns-stream
    profiles:
      - full
      - back-end

  collector-ps4eu:
    build: apps/stream-collector
    env_file: apps/stream-collector/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - PS2_ENVIRONMENT=ps2ps4eu
    restart: unless-stopped
    networks:
      - ns-stream
    profiles:
      - full
      - back-end

  collector-ps4us:
    build: apps/stream-collector
    env_file: apps/stream-collector/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - PS2_ENVIRONMENT=ps2ps4us
    restart: unless-stopped
    networks:
      - ns-stream
    profiles:
      - full
      - back-end

  manifold:
    build: apps/stream-manifold
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '${MANIFOLD_PORT:-3000}:3000'
    env_file: apps/stream-manifold/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - RABBITMQ_STREAM_EXCHANGE=cr-stream
      - APP_PORT=3000
    profiles:
      - full


networks:
  ns-stream:
    name: 'ns-stream'
