version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '5672:${RABBITMQ_PORT:-5672}'
      - '15672:${RABBITMQ_MANAGEMENT_PORT:-15672}'
    env_file: .env

  collector-pc: &collector
    image: ghcr.io/nanite-systems/stream-collector
    build:
      dockerfile: Dockerfile
      args:
        APP_NAME: stream-collector
    env_file:
      - .env
      - apps/stream-collector/.env
    environment: &collector_environment
      RMQ_URLS: amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      APP_PORT: 3000
      ESS_ENVIRONMENT: ps2
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - ns-stream
    ports:
      - '${COLLECTOR_PC_PORT:-3002}:3000'
    profiles:
      - full
      - back-end

  collector-ps4eu:
    <<: *collector
    environment:
      <<: *collector_environment
      ESS_ENVIRONMENT: ps2ps4eu
    ports:
      - '${COLLECTOR_PS4EU_PORT:-3003}:3000'

  collector-ps4us:
    <<: *collector
    environment:
      <<: *collector_environment
      ESS_ENVIRONMENT: ps2ps4us
    ports:
      - '${COLLECTOR_PS4US_PORT:-3004}:3000'

  api:
    image: ghcr.io/nanite-systems/stream-api
    build:
      dockerfile: Dockerfile
      args:
        APP_NAME: stream-api
    restart: unless-stopped
    env_file:
      - .env
      - apps/stream-api/.env
    environment:
      RMQ_URLS: amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      APP_PORT: 3000
    depends_on:
      - rabbitmq
    networks:
      - ns-stream
    ports:
      - '${API_PORT:-3001}:3000'

  manifold:
    image: ghcr.io/nanite-systems/stream-manifold
    build:
      dockerfile: Dockerfile
      args:
        APP_NAME: stream-manifold
    restart: unless-stopped
    depends_on:
      - collector-pc
      - collector-ps4eu
      - collector-ps4us
      - api
      - rabbitmq
    networks:
      - ns-stream
    ports:
      - '${MANIFOLD_PORT:-3000}:3000'
    env_file:
      - .env
      - apps/stream-manifold/.env
    environment:
      RMQ_URLS: amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      APP_PORT: 3000
    profiles:
      - full

networks:
  ns-stream:
    name: 'ns-stream'
