version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '5672:${RABBITMQ_PORT:-5672}'
      - '15672:${RABBITMQ_MANAGEMENT_PORT:-15672}'
    env_file: .env
  collector:
    build: apps/stream-collector
    env_file: apps/stream-collector/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - RABBITMQ_COLLECTOR_EXCHANGE_NAME=cr-collector
    restart: unless-stopped
    networks:
      - ns-stream
    profiles:
      - full
      - back-end
  multiplexer:
    build: apps/stream-multiplexer
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '${MULTIPLEXER_PORT:-3000}:3000'
    env_file: apps/stream-multiplexer/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - RABBITMQ_COLLECTOR_EXCHANGE=cr-collector
      - RABBITMQ_STREAM_EXCHANGE=cr-stream
      - APP_PORT=3000
    profiles:
      - full
      - back-end
  manifold:
    build: apps/stream-manifold
    restart: unless-stopped
    networks:
      - ns-stream
    ports:
      - '${MANIFOLD_PORT:-8000}:3000'
    env_file: apps/stream-manifold/.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_PASS:-guest}:${RABBITMQ_DEFAULT_USER:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}
      - RABBITMQ_STREAM_EXCHANGE=cr-stream
      - MULTIPLEXER_ENDPOINT=http://multiplexer:3000
      - APP_PORT=3000
    profiles:
      - full

networks:
  ns-stream:
    name: 'ns-stream'
