name: Docker

on:
  push:
    tags:
      - 'stream-api@*'
      - 'stream-auth@*'
      - 'stream-collector@*'
      - 'stream-manifold@*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: release
    if: github.repository == 'nanite-systems/stream'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --silent

      - name: Build and push
        run: pnpm nx container ${GITHUB_REF_NAME%@*} --push
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_CACHE_TO: type=gha,mode=max
          INPUT_CACHE_FROM: type=gha
