name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lerna bootstrap
      - name: Compile
        run: lerna build
