name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-test:
    name: Compile test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --silent

      - name: Compile
        run: pnpm nx run-many --target=build
